# Site settings
title: Emmanouil Katefidis
description: 'Undergraduate Student of Computer Engineering & Informatics Dept.'
url: 'https://www.katefidis.ga'
baseurl: ''
google_analytics: 'UA-83279918-2'
disqus_shortname: 'katefidis'

author:
  name: 'Emmanouil Katefidis'
  email: katefidis@ceid.upatras.gr
  twitter_username: man0ssl
  #facebook_username: man0ssl
  github_username:  man0s
  linkedin_username:  man0s

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
